// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sort.proto

#include "sort.pb.h"
#include "sort.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace mynamespace {

static const char* SortService_method_names[] = {
  "/mynamespace.SortService/SortNumbers",
};

std::unique_ptr< SortService::Stub> SortService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SortService::Stub> stub(new SortService::Stub(channel, options));
  return stub;
}

SortService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SortNumbers_(SortService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SortService::Stub::SortNumbers(::grpc::ClientContext* context, const ::mynamespace::SortRequest& request, ::mynamespace::SortResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mynamespace::SortRequest, ::mynamespace::SortResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SortNumbers_, context, request, response);
}

void SortService::Stub::async::SortNumbers(::grpc::ClientContext* context, const ::mynamespace::SortRequest* request, ::mynamespace::SortResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mynamespace::SortRequest, ::mynamespace::SortResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SortNumbers_, context, request, response, std::move(f));
}

void SortService::Stub::async::SortNumbers(::grpc::ClientContext* context, const ::mynamespace::SortRequest* request, ::mynamespace::SortResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SortNumbers_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mynamespace::SortResponse>* SortService::Stub::PrepareAsyncSortNumbersRaw(::grpc::ClientContext* context, const ::mynamespace::SortRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mynamespace::SortResponse, ::mynamespace::SortRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SortNumbers_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mynamespace::SortResponse>* SortService::Stub::AsyncSortNumbersRaw(::grpc::ClientContext* context, const ::mynamespace::SortRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSortNumbersRaw(context, request, cq);
  result->StartCall();
  return result;
}

SortService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SortService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SortService::Service, ::mynamespace::SortRequest, ::mynamespace::SortResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SortService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mynamespace::SortRequest* req,
             ::mynamespace::SortResponse* resp) {
               return service->SortNumbers(ctx, req, resp);
             }, this)));
}

SortService::Service::~Service() {
}

::grpc::Status SortService::Service::SortNumbers(::grpc::ServerContext* context, const ::mynamespace::SortRequest* request, ::mynamespace::SortResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace mynamespace

